# Generated by Django 5.0 on 2025-07-16 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0010_coffeeshop_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summarizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.coffeeshop')),
            ],
        ),
    ]
