# Generated by Django 5.0 on 2025-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='is_top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
