# Generated by Django 5.0 on 2025-06-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review_one_review_per_user_per_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
