# Generated by Django 5.0 on 2025-06-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coffeeshop_latitude_coffeeshop_longitude'),
        ('home', '0007_alter_review_rating'),
    ]

    operations = [
    ]
