# Generated by Django 5.2.1 on 2025-07-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coffeeshop_latitude_coffeeshop_longitude'),
        ('home', '0007_alter_review_rating'),
    ]

    operations = [
    ]
