# Generated by Django 5.0 on 2025-07-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20250709_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
