# Generated by Django 5.0 on 2025-06-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20250630_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
