# Generated by Django 5.0 on 2025-07-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('osm', 'OpenStreetMap')], default='local', max_length=10),
        ),
    ]
