# Generated by Django 5.0 on 2025-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_osmfavoritedshop_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='osm_shop_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
