# Generated by Django 5.0 on 2025-07-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_review_osm_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.coffeeshop'),
        ),
    ]
