# Generated by Django 5.0 on 2025-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_review_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='osm_shop_id',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('osm', 'OpenStreetMap')], default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
        migrations.DeleteModel(
            name='OSMFavoritedShop',
        ),
    ]
